# Generated by Django 5.2.7 on 2025-10-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_management'),
        ('courses', '0002_remove_lesson_video_url_lesson_video_id'),
        ('enrollments', '0002_rename_enrollments_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', through='enrollments.Enrollment', to='courses.course'),
        ),
    ]
