# Generated by Django 5.2.7 on 2025-10-15 08:49

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
