# Generated by Django 5.2.7 on 2025-10-15 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_usersprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2025, 10, 15, 10, 4, 57, 622048, tzinfo=datetime.timezone.utc)),
        ),
    ]
