# Generated by Django 5.2.7 on 2025-10-15 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_usersprofile_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
