# Generated by Django 5.2.7 on 2025-10-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_management'),
        ('courses', '0002_remove_lesson_video_url_lesson_video_id'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollments',
            new_name='Enrollment',
        ),
    ]
