# Generated by Django 5.2.7 on 2025-10-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_rename_enrollments_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='progress',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
