# Generated by Django 5.2.7 on 2025-10-16 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_completed_lesson_progress'),
        ('enrollments', '0003_alter_enrollment_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_viewed_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.lesson'),
        ),
    ]
