# Generated by Django 5.2.7 on 2025-10-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(default='temp', max_length=20),
            preserve_default=False,
        ),
    ]
