# Generated by Django 5.2.7 on 2025-10-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
