# Generated by Django 5.2.7 on 2025-10-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_about_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='progress',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
