# Generated by Django 5.2.7 on 2025-10-22 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_usersprofile_date_joined'),
        ('courses', '0009_lessonquestion_questionoption_studentanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='progress',
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('completed', models.BooleanField(default=False)),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='authentication.student')),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
