# Generated by Django 5.2.7 on 2025-10-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_lesson_completed_remove_lesson_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='percentage',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
