# Generated by Django 5.2.7 on 2025-10-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='progress',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
    ]
