# Generated by Django 5.2.7 on 2025-10-31 10:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_announcement_lessonassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='CourseAnnouncement',
        ),
    ]
