# Generated by Django 5.2.7 on 2025-11-08 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonassignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lessonassignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lessonassignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonassignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonassignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_files/'),
        ),
    ]
