# Generated by Django 5.2.7 on 2025-11-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_lessonassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
