# Generated by Django 5.2.7 on 2025-11-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_assignmentsubmission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonassignment',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
