# Generated by Django 5.2.7 on 2025-11-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_lessonassignment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonassignment',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
