# Generated by Django 5.2.7 on 2025-11-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_lessonassignment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
